### ISSUE TITLE
Unable to load r java package

### ISSUE THREAD

**Issue by l3ikrant** [unhcr/koboloadeR#39]
I am using in Windows and
 install_github("unhcr/koboloadeR", ref = "gh-pages") 
 fails due to ..

it searches rJava in users/USER/Documents/R/win-library/3.5/rJava/libs/x64/rJava.dll
path back slash (/)
But the file exists in C:\Users\USER\Documents\R\win-library\3.5\rJava\libs\x64
(front slash \)

**Comment by l3ikrant** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/7446485/56015095-7f20d580-5d17-11e9-98ca-d2839553616e.png)

**Comment by awemulya** [comment]
Same Happened to my windows a months ago. I installed 64 bit R, 64 bit Java. And still the problem occured.
I switched to Ubuntu.

**Comment by Edouard-Legoupil** [comment]
As you can see in the readme - 
If you get this error:

Error: package or namespace load failed for 'rJava'

It could be because you have a 64bit version of R, but have a 32bit version of Java. Check this thread for guidance: https://stackoverflow.com/questions/37735108/r-error-onload-failed-in-loadnamespace-for-rjava

Find where your Java is installed then set it up in your environment - You may need to restrart Rstudio once done
 For instance - depending on where Java is installed, use the command:
`Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre7') # for 64-bit version`

**Comment by awemulya** [comment]
After Trying
For instance - depending on where Java is installed, use the command:
Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre7') # for 64-bit version

library(rJava)
still fails rJava doesnot exists for R 3.*.*

I do have both 32 bit and 64 bit R and Rstudio May be uninstalling 32 bit r and rstudio and  using Only One helps.

**Comment by Edouard-Legoupil** [comment]
Did you try to close Rstudio and reopen it before launching Rjava?

This addressed the issue when I faced it...

**Comment by awemulya** [comment]
Sorry for late response. But I am sure the mistake was from myside with some Java version or path problem. I switched to ubuntu and  its working fine.
